#!/bin/sh

rm -rf solution
mkdir solution

mkdir solution/strings
cp -a strings/{Makefile,unique.c,parity.c,set.h,table.c} solution/strings

mkdir solution/generic
cp -a generic/{Makefile,unique.c,parity.c,counts.c,set.h,table.c} solution/generic

tar cvf solution.tar ./solution
rm -rf solution
